export const NOTI_READY_TO_BUY = "READY TO BUY PRODUCTS!";
export const NOTI_GREATER_THAN_ONE = "QUANTITY MUST EQUAL OR GREATER THAN ONE!";
export const NOTI_ACT_ADD = "ADDED PRODUCT SUCCESSFULL !!!";
export const NOTI_ACT_UPDATE = "UPDATED PRODUCT SUCCESSFULL !!!";
export const NOTI_ACT_DELETE = "DELETED PRODUCT SUCCESSFULL !!!";
export const NOTI_EMPTY_PRODUCT = "EMPTY PRODUCT !!!";

export const CART_FROM_LOCAL_STORAGE = "cart123123";
